### ISSUE TITLE
pub_socket.connect Error

### ISSUE THREAD

**Issue by vivekgr92** [commaai/cereal#16]
When I try to run the stress.py, 
I get an error saying
terminate called after throwing an instance of 'YAML::BadFile'
  what():  bad file
Aborted (core dumped)

When I used breakpoints I could see that the error is caused in this line pub_socket.connect(c,"controlsState")

Any help ??

**Comment by pd0wm** [comment]
This is a problem if the `service_list.yaml` file was not found in the expected location. We replaced that logic now by converting it into a header file first. Are you still having this problem with the latest revision?
