### ISSUE TITLE
Is there any benchmark between ZMQ pub/sub and msgq?

### ISSUE THREAD

**Issue by Grabber** [commaai/cereal#186]
Thank you so much for sharing this piece of code, very interesting!

Could you please explain the reasons why ZMQ pub/sub (or maybe nng) ins't fast enough? Or how faster is msgq (shm) compared to ZMQ?

**Comment by geohot** [comment]
ZMQ puts the data through the kernel, making multiple copies. msgq doesn't, and uses shared memory between the processes. That's the major difference.

**Comment by Grabber** [comment]
@geohot

At what resolution the frames (or raw data) are going over the pub/sub? I found msgq very interesting because years ago I have implemented a pub/sub with ZMQ but I was sending frames at 320x240 or (320x240x3*byte) and at that time I couldn't realize any impact on the CPU.

Have you tested it with 1 pub and dozen of subs to analyze how it scales?

Thank you so much, congrats for the 3!
