### ISSUE TITLE
Set ZeroMQ snd/rcv watermark and linger?

### ISSUE THREAD

**Issue by Grabber** [commaai/cereal#190]
Isn't it interesting to set snd/rcv watermark and linger ZeroMQ options to avoid overflooding the in memory pub/sub queues?

Here is an example for setting it once for all instance sockets, but it can also be done per socket instance.
```
zsys_set_linger(0);
size_t hwm = 30;
zsys_set_sndhwm(hwm);
zsys_set_rcvhwm(hwm);
```

On `msgq` implementation is there any pub/sub queue size limit?

**Comment by adeebshihadeh** [comment]
This isn't really relevant for our use cases in openpilot as we mostly use msgq, however we'd consider a PR if you've got specific suggestions on improving another use case you may have.
