### ISSUE TITLE
VisionIPC doesn't work for remote ip address

### ISSUE THREAD

**Issue by unomove** [commaai/cereal#273]
When going through the code, the visionipc_client is binded to "127.0.0.1"
sock = SubSocket::create(msg_ctx, get_endpoint_name(name, type), "127.0.0.1", conflate, false);

But when I hard-coded it with some ip (192.168.1.10), it still doesn't work.

I tried it with the following commands:
```
# in host machine: ip: 192.168.1.10
export ZMQ=1
replay --demo

# in client machine: ip: 192.168.1.123
export ZMQ=1
python ui.py 192.168.1.10
```

**Comment by geohot** [comment]
visionipc doesn't make a copy of the frames, it passes around a buffer in the same RAM. Therefore it won't work across the network. But if you want, write an alternative implementation that does and if it's clean we'll upstream it!
